language: python
python:
    - "2.7"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
before_install:
    - "sudo apt-get update -qq"
    - "sudo apt-get install -y gfortran"
    - "curl -O https://cran.r-project.org/src/base/R-4/R-4.1.0.tar.gz"
    - "tar -xzf R-4.1.0.tar.gz"
    - "(cd R-4.1.0; ./configure --with-x=no --prefix=/usr --enable-R-shlib && make && sudo make install)"
    - "curl -O http://www.rforge.net/Rserve/snapshot/Rserve_1.8-8.tar.gz"
    - "sudo PKG_CPPFLAGS=-DNODAEMON  R CMD INSTALL Rserve_1.8-8.tar.gz"
install: "pip install -r requirements.txt"
script:
    - "py.test testing"
